version: 2

cache-defaults: &cache-defaults
  keys:
    - oid-v1-{{ arch }}-{{ checksum "yarn.lock" }}
cache-cypress: &cache-cypress
  keys:
    - oid-cypress-v1-{{ arch }}-{{ checksum "yarn.lock" }}
aliases:
  - &cache-modules
    key: oid-v1-{{ arch }}-{{ checksum "yarn.lock" }}
    paths: &cache-modules-paths
      - ~/.cache/yarn
      - node_modules
      # Necessary so that linting is faster on CI
      - .eslintcache
  - &cache-cypress-modules
    key: oid-cypress-v1-{{ arch }}-{{ checksum "yarn.lock" }}
    paths: &cache-cypress-paths
      - ~/.cache/Cypress
  - &yarn
    name: Installing Dependencies
    command: yarn install --non-interactive --frozen-lockfile --cache-folder ~/.cache/yarn
  - &build
    name: Building Project
    command: yarn build
  - &export
    name: Export Project
    command: yarn export
jobs:
  build:
    docker:
      - image: circleci/node:dubnium-browsers
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          <<: *cache-defaults
      - restore_cache:
          <<: *cache-cypress
      - run: *yarn
      - save_cache: *cache-modules
      - save_cache: *cache-cypress-modules
      - run: *build
  lint:
    docker:
      - image: circleci/node:dubnium-browsers
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          <<: *cache-defaults
      - run: *yarn
      - save_cache: *cache-modules
      - run:
          name: Lint
          command: yarn lint
  test-unit:
    docker:
      - image: circleci/node:dubnium-browsers
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          <<: *cache-defaults
      - run: *yarn
      - save_cache: *cache-modules
      - run:
          name: Jest Testing
          command: yarn test --ci
      # - run:
      #     name: Upload coverage
      #     command: bash <(curl -s https://codecov.tools.a.intuit.com/bash)  -X s3
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: coverage/junit/
  release:
    docker:
      - image: circleci/node:dubnium-browsers
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          <<: *cache-defaults
      - run: *yarn
      - save_cache: *cache-modules
      - run: *export
      - run:
          name: Assume Github Role
          command: 'git config --global user.email "lshadler13@gmail.com" && git config --global user.name "lshadler"'
      - run:
          name: Auto Shipit
          command: |
            yarn release
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
      - test-unit:
          requires:
            - build
      - lint:
          requires:
            - build
      - release:
          requires:
            - build
            - test-unit
            - lint